name: Tests
on:
  push:
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader"
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
      - name: Run tests
        run: php vendor/bin/phpunit --bootstrap=tests/bootstrap.php --no-coverage
